# Generated by Django 5.2.6 on 2025-10-02 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('objet', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('categorie', models.CharField(choices=[('Principale', 'Principale'), ('Notification', 'Notification')], default='Principale', max_length=20)),
                ('status', models.CharField(choices=[('Brouillons', 'Brouillons'), ('Planifié', 'Planifié'), ('Archiver', 'Archiver'), ('Corbeille', 'Corbeille'), ('Suivie', 'Suivie')], default='Brouillons', max_length=20)),
                ('date_envoie', models.DateTimeField(auto_now_add=True)),
                ('date_programmee', models.DateTimeField(blank=True, null=True)),
                ('est_lu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Destinataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinataire', models.EmailField(max_length=254)),
                ('nom_destinataire', models.CharField(max_length=100)),
                ('prenom_destinataire', models.CharField(max_length=100)),
                ('type_destinataire', models.CharField(choices=[('A', 'A'), ('CC', 'CC'), ('CCI', 'CCI')], default='A', max_length=3)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinataires', to='Appli_WEB_Mail.message')),
            ],
        ),
        migrations.CreateModel(
            name='Confidentiel',
            fields=[
                ('id_confidentiel', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('est_confidentiel', models.BooleanField(default=False)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('heure_expiration', models.TimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confidentiel', to='Appli_WEB_Mail.message')),
            ],
        ),
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id_attachement', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='fichiers/')),
                ('lien', models.URLField(blank=True, null=True)),
                ('drive', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachements', to='Appli_WEB_Mail.message')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_utilisateur', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=20)),
                ('photo_de_profil', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL),
        ),
    ]
